apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: event-listener
spec:
  serviceAccountName: tekton-pipeline
  triggers:
    - name: github-listener
      # - name: github-listener
      #   interceptors:
      #     - github:
      #         secretRef:
      #           secretName: github-secret
      #           secretKey: secretToken
      #         eventTypes:
      #           - pull_request
      #     - cel:
      #         filter: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: trigger-binding
      template:
        ref: trigger-template
