kind: Secret
apiVersion: v1
metadata:
  name: my-dockerconfig
data:
  config.json: # ... encode config.json ...

# config.json format
#{
#    "auths": {
#        "https://index.docker.io/v1/": {
#            // echo -n USER:PASSWORD | base64
#            "auth": "..."
#        }
#    }
#}
