apiVersion: v1
kind: ConfigMap
metadata:
  name: manifests
data:
  deployment.yaml: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: demo-dep
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: demo-dep
      template:
        metadata:
          labels:
            app: demo-dep
        spec:
          containers:
            - name: myapp
              image: micheliac/pipeline-test:latest
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8080
                  name: http
